baseURL = "https://goodguysracing.github.io/goodguys_website/"
theme = "gohugo-theme-ananke"
languageCode = 'en-us'
title = 'Good Guys Racing'

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Roster"
url = "/roster/"
weight = 2

[[menu.main]]
name = "Partners"
url = "/partners/"
weight = 3

[[menu.main]]
name = "Schedule"
url = "/schedule/"
weight = 4

[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 5

[params]
custom_css  = ["custom.css"]
mainSections = ['news','Kreatives']
body_classes = "couture bg-near-white"

[[params.partners]]
  name = "Assos"
  logo = "/images/logos/assos.png"
  url = "https://www.assos.com/"

[[params.partners]]
  name = "Cervelo"
  logo = "/images/logos/cervelo.png"
  url = "https://www.cervelo.com/"

[[params.partners]]
  name = "oakley"
  logo = "/images/logos/oakley.png"
  url = "https://www.oakley.com/"

[[params.partners]]
  name = "strictly"
  logo = "/images/logos/strictly.png"
  url = "https://www.strictlybicycles.com/"

[[params.partners]]
  name = "vintus"
  logo = "/images/logos/vintus.png"
  url = "https://www.vintus.com/"

[[params.partners]]
  name = "undrbudr"
  logo = "/images/logos/undrbudr.png"
  url = "https://www.undrbudr.com/"