baseURL = "https://goodguysracing.github.io/goodguys_website/"
theme = "gohugo-theme-ananke"
languageCode = 'en-us'
title = 'Good Guys Racing'

[[menu.main]]
name = "Roster"
url = "/roster/"
weight = 1

[[menu.main]]
name = "Partners"
url = "/partners/"
weight = 2

[[menu.main]]
name = "Schedule"
url = "/schedule/"
weight = 3

[[menu.main]]
name = "Mission"
url = "/mission/"
weight = 4

[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
custom_css  = ["custom.css"]
mainSections = ['news','Kreatives']
body_classes = "couture bg-near-white"

[[params.ananke_socials]]
name = "instagram"
url = "https://www.instagram.com/goodguysnyc"

[[params.partners]]
  name = "Assos"
  logo_footer = "/images/logos/assos.png"
  logo_main = "/images/logos/assos_svg.png"
  url = "https://www.assos.com/"
  description = "Assos makes the best cycling clothing in the world"

[[params.partners]]
  name = "Cervelo"
  logo_footer = "/images/logos/cervelo.png"
  logo_main = "/images/logos/cervelo.svg"
  url = "https://www.cervelo.com/"
  description = "Cervelo is a leading bike manufacturer."

[[params.partners]]
  name = "oakley"
  logo_footer = "/images/logos/oakley.png"
  logo_main = "/images/logos/oakley.svg"
  url = "https://www.oakley.com/"
  description = "Oakley provides high-quality sports eyewear."

[[params.partners]]
  name = "strictly"
  logo_footer = "/images/logos/strictly_white_transparent.png"
  logo_main = "/images/logos/strictly_main.png"
  url = "https://www.strictlybicycles.com/"

[[params.partners]]
  name = "vintus"
  logo_footer = "/images/logos/vintus.png"
  logo_main = "/images/logos/vintus_transparent.png"
  url = "https://www.vintus.com/"

[[params.partners]]
  name = "undrbudr"
  logo_footer = "/images/logos/undrbudr_white_transparent.png"
  logo_main = "/images/logos/undrbudr_transparent.png"
  url = "https://www.undrbudr.com/"

  [[params.partners]]
  name = "strategio"
  logo_footer = "/images/logos/strategio_transparent.png"
  logo_main = "/images/logos/strategio_main.png"
  url = "https://www.strategio.tech"

  [[params.partners]]
  name = "jtrain"
  logo_footer = "/images/logos/jtrain_white_transparent.png"
  logo_main = "/images/logos/jtrain_black_transparent.png"
  url = "https://jtrainwellness.com"